name: .NET Core Build & Verification

on:
  push:
    branches: [ "develop", "master", "main" ]
  pull_request:
    branches: [ "develop", "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore TutorPlatform.slnx

    - name: Build Solution
      run: dotnet build TutorPlatform.slnx --no-restore --configuration Release
